kind: "BuildConfig"
apiVersion: "v1"
metadata:
  name: "nodejs-sample-pipeline"
spec:
  source:
    git:
      uri: https://github.com/praveenrachamreddy/openshiftcicd.git
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfilePath: /jenkinsfile
    type: JenkinsPipeline
